# Generated by Django 3.2 on 2021-09-05 13:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('642fcd36-a288-407d-b1c0-1eee484e6237'), primary_key=True, serialize=False, verbose_name='Application id')),
                ('email', models.CharField(max_length=20, unique=True, verbose_name='Applicant email')),
                ('first_name', models.CharField(max_length=20, unique=True, verbose_name='Applicant first name')),
                ('last_name', models.CharField(max_length=20, unique=True, verbose_name='Applicant last name')),
                ('status', models.CharField(max_length=20, verbose_name='Application status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bbe1fff7-cecf-486d-b1f0-09d2a18f3655'), primary_key=True, serialize=False, verbose_name='Basic id')),
                ('basic_name', models.CharField(max_length=20, unique=True, verbose_name='Basic name')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('90c440b3-fcf7-426e-b6e0-58d33fd6840d'), primary_key=True, serialize=False, verbose_name='Permission id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Permission name')),
                ('description', models.CharField(max_length=500, verbose_name='Permission description')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('b876e735-be5c-4dd1-8853-bf3b8a1992fb'), primary_key=True, serialize=False, verbose_name='Person unique id')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Person first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Person last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Person email')),
                ('password', models.CharField(max_length=150, verbose_name='Person password')),
                ('address', models.CharField(max_length=150, verbose_name='Person address')),
                ('gender', models.CharField(max_length=150, verbose_name='Person gender')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Person phone number')),
                ('date_of_birth', models.DateTimeField(verbose_name='Person dob')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('permission', models.ManyToManyField(to='app.Permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cb790313-08a5-4a66-b157-679d7bc6a6df'), primary_key=True, serialize=False, verbose_name='Session id')),
                ('session_name', models.CharField(max_length=20, unique=True, verbose_name='Session name')),
                ('session_start', models.DateTimeField(verbose_name='Session Start')),
                ('session_end', models.DateTimeField(verbose_name='Session Start')),
                ('session_status', models.CharField(max_length=20, verbose_name='Session status')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eb7fada4-34c7-417d-90ab-2931d1afa181'), primary_key=True, serialize=False, verbose_name='Subject id')),
                ('subject_name', models.CharField(max_length=20, unique=True, verbose_name='Subject name')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2d4e95cf-0fc3-4010-99e8-38a4580acaba'), primary_key=True, serialize=False, verbose_name='Term id')),
                ('term_name', models.CharField(max_length=20, unique=True, verbose_name='Term name')),
                ('term_status', models.CharField(max_length=20, verbose_name='Term status')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a6f3427c-f2ad-4915-853a-ba60edf17859'), primary_key=True, serialize=False, verbose_name='Role id')),
                ('admin_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Admission Number')),
                ('basic', models.ManyToManyField(to='app.Basic')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ebdc5eb3-f321-4c57-80c9-d18833196cab'), primary_key=True, serialize=False, verbose_name='Role id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Role name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Role description')),
                ('permission', models.ManyToManyField(to='app.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ManyToManyField(to='app.Role'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('711f5b3c-e59a-43e7-bfff-920fd4bd03f6'), primary_key=True, serialize=False, verbose_name='Role id')),
                ('staff_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Staff Number')),
                ('employment_date', models.DateTimeField(verbose_name='Employment date')),
                ('employment_status', models.CharField(blank=True, max_length=500, null=True, verbose_name='Staff Number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.person')),
            ],
        ),
        migrations.AddField(
            model_name='basic',
            name='subject',
            field=models.ManyToManyField(to='app.Subject'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('896709b9-692e-4d02-acac-3ecf22a60ec1'), primary_key=True, serialize=False, verbose_name='Attendance id')),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8fed0f4e-cd0d-4736-b6fd-1e2c2ccb2084'), primary_key=True, serialize=False, verbose_name='Arm id')),
                ('arm_name', models.CharField(max_length=20, unique=True, verbose_name='Arm name')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.basic')),
            ],
        ),
    ]
