# Generated by Django 3.2 on 2021-09-08 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_no',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Application number'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_score',
            field=models.IntegerField(default=None, verbose_name='Application Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='basic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='app.basic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admin_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Admission Year'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2edc28f-f3c9-4a1f-aaa9-5450a62416db'), primary_key=True, serialize=False, verbose_name='Application id'),
        ),
        migrations.AlterField(
            model_name='arm',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d86e93fe-71a5-4435-89df-8b42fd26d10f'), primary_key=True, serialize=False, verbose_name='Arm id'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cc0b490-7c92-4fee-8877-7ebb86cdfce6'), primary_key=True, serialize=False, verbose_name='Attendance id'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04748bf6-3577-4f9e-bbe1-bbad851c0930'), primary_key=True, serialize=False, verbose_name='Basic id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('124d3b35-4712-4854-a9f9-0fc361025715'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1569b7f9-4175-4883-aa84-70f27b66cb7e'), primary_key=True, serialize=False, verbose_name='Permission id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42399c08-2259-46a0-ae24-748aa15e9757'), primary_key=True, serialize=False, verbose_name='Person unique id'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20924fbe-ffbb-48df-b7b3-0344b085ebff'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc1af5a4-e481-4d8b-8642-25dc393c6541'), primary_key=True, serialize=False, verbose_name='Session id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b64e8914-8a8b-4c79-80f2-695649671323'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8d57ef9-c28c-4f36-9992-33ceef3868ce'), primary_key=True, serialize=False, verbose_name='Subject id'),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1a58e1d-36ce-430d-9693-59c52585e4ef'), primary_key=True, serialize=False, verbose_name='Term id'),
        ),
    ]
