# Generated by Django 3.2 on 2021-10-01 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210908_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='arm',
            name='basic_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25baa12a-3f48-44b9-aebb-e1cc2704dc5d'), primary_key=True, serialize=False, verbose_name='Application id'),
        ),
        migrations.AlterField(
            model_name='arm',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a817e63-cbdf-4724-98b9-92f85f10dc28'), primary_key=True, serialize=False, verbose_name='Arm id'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('359907bb-1b73-4524-a649-b6b41fcad2a3'), primary_key=True, serialize=False, verbose_name='Attendance id'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc123efa-d333-4c43-a4fe-672afd760815'), primary_key=True, serialize=False, verbose_name='Basic id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b867899-3d0d-4923-945e-b1037fb1beee'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a023b5f-dc97-4a85-b6b9-289216f309e8'), primary_key=True, serialize=False, verbose_name='Permission id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93379aa1-0ff1-477f-9712-1c6400efc949'), primary_key=True, serialize=False, verbose_name='Person unique id'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b090d61-fc86-43be-a67c-469c91056ca4'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a7849fa-c729-4aad-9026-aee4034a800f'), primary_key=True, serialize=False, verbose_name='Session id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78c8bf8b-e77a-49a7-8e55-9264b4ad603f'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.UUID('038074a1-b7aa-4a40-a4cd-db57c540718a'), primary_key=True, serialize=False, verbose_name='Subject id'),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4ade193-f660-47c2-8d87-fcf5444466bd'), primary_key=True, serialize=False, verbose_name='Term id'),
        ),
    ]
